#!/usr/bin/env bash
# .compliance/scripts/auth0.sh
# SOC 2 evidence collection for Auth0
# Requires: AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET env vars
# Config:   auth0.config.json { "domain": "company.us.auth0.com" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
AUTH0_DOMAIN=$(jq -r '.domain' "$CONFIG")

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Auth0 - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Auth0"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Get Management API token
TOKEN=$(curl -sf --request POST \
  --url "https://$AUTH0_DOMAIN/oauth/token" \
  --header 'content-type: application/json' \
  --data "{\"client_id\":\"$AUTH0_CLIENT_ID\",\"client_secret\":\"$AUTH0_CLIENT_SECRET\",\"audience\":\"https://$AUTH0_DOMAIN/api/v2/\",\"grant_type\":\"client_credentials\"}" \
  | jq -r '.access_token' || echo "")

if [ -z "$TOKEN" ]; then
  echo "| Auth0 API | **authentication failed** | Auth0 | \`/oauth/token\` | Could not obtain Management API token |" >> "$OUT"
else
  # MFA factors
  factors=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "https://$AUTH0_DOMAIN/api/v2/guardian/factors" || echo "[]")
  enabled=$(echo "$factors" | jq '[.[] | select(.enabled == true)] | length')
  echo "| MFA factors enabled | **${enabled}** | Auth0 | \`/api/v2/guardian/factors\` | ${enabled} MFA factor types enabled |" >> "$OUT"

  # Active users count
  users=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "https://$AUTH0_DOMAIN/api/v2/users?include_totals=true&per_page=0" || echo '{"total":0}')
  user_count=$(echo "$users" | jq '.total // 0')
  echo "| Total users | **${user_count}** | Auth0 | \`/api/v2/users\` | ${user_count} total users |" >> "$OUT"

  # Brute force protection
  brute=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "https://$AUTH0_DOMAIN/api/v2/attack-protection/brute-force-protection" || echo '{}')
  bf_enabled=$(echo "$brute" | jq -r '.enabled // false')
  echo "| Brute force protection | **${bf_enabled}** | Auth0 | \`/api/v2/attack-protection/brute-force-protection\` | Brute force protection enabled: ${bf_enabled} |" >> "$OUT"

  # Suspicious IP throttling
  sus_ip=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "https://$AUTH0_DOMAIN/api/v2/attack-protection/suspicious-ip-throttling" || echo '{}')
  sip_enabled=$(echo "$sus_ip" | jq -r '.enabled // false')
  echo "| Suspicious IP throttling | **${sip_enabled}** | Auth0 | \`/api/v2/attack-protection/suspicious-ip-throttling\` | Suspicious IP throttling enabled: ${sip_enabled} |" >> "$OUT"

  # Connections
  conns=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "https://$AUTH0_DOMAIN/api/v2/connections" || echo "[]")
  conn_count=$(echo "$conns" | jq 'length')
  echo "| Connections | **${conn_count}** | Auth0 | \`/api/v2/connections\` | ${conn_count} connections configured |" >> "$OUT"
fi

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: auth0 evidence written to $OUT"
