#!/usr/bin/env bash
# .compliance/scripts/bamboohr.sh
# SOC 2 evidence collection for BambooHR
# Requires: BAMBOOHR_API_KEY env var
# Config:   bamboohr.config.json { "subdomain": "company" }
# Privacy: Only aggregate counts — no PII
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
SUBDOMAIN=$(jq -r '.subdomain' "$CONFIG")
AUTH=$(echo -n "$BAMBOOHR_API_KEY:x" | base64)

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# BambooHR - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: BambooHR"
  echo "> Privacy: Aggregate counts only — no PII"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Employee directory (count only)
directory=$(curl -sf -H "Authorization: Basic $AUTH" \
  -H "Accept: application/json" \
  "https://api.bamboohr.com/api/gateway.php/${SUBDOMAIN}/v1/employees/directory" || echo '{"employees":[]}')
total=$(echo "$directory" | jq '.employees | length')
active=$(echo "$directory" | jq '[.employees[] | select(.status == "Active" or .status == null)] | length' 2>/dev/null || echo "$total")
echo "| Employee count | **${active} active / ${total} total** | BambooHR | \`/v1/employees/directory\` | ${active} active employees of ${total} total |" >> "$OUT"

# Time-off policy types
timeoff=$(curl -sf -H "Authorization: Basic $AUTH" \
  -H "Accept: application/json" \
  "https://api.bamboohr.com/api/gateway.php/${SUBDOMAIN}/v1/meta/time_off/types" || echo '{"timeOffTypes":[]}')
to_count=$(echo "$timeoff" | jq '.timeOffTypes | length' 2>/dev/null || echo "0")
echo "| Time-off policies | **${to_count}** | BambooHR | \`/v1/meta/time_off/types\` | ${to_count} time-off policy types configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: bamboohr evidence written to $OUT"
