#!/usr/bin/env bash
# .compliance/scripts/datadog.sh
# SOC 2 evidence collection for Datadog
# Requires: DATADOG_API_KEY, DATADOG_APP_KEY env vars
# Config:   datadog.config.json { "site": "datadoghq.com" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
SITE=$(jq -r '.site // "datadoghq.com"' "$CONFIG")
BASE="https://api.${SITE}"

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Datadog - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Datadog"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Active monitors (use search endpoint to get total count)
monitors=$(curl -sf \
  -H "DD-API-KEY: $DATADOG_API_KEY" \
  -H "DD-APPLICATION-KEY: $DATADOG_APP_KEY" \
  "$BASE/api/v1/monitor/search" || echo '{}')
total=$(echo "$monitors" | jq '.metadata.total_count // 0')
echo "| Active monitors | **${total}** | Datadog | \`/api/v1/monitor/search\` | ${total} monitors configured |" >> "$OUT"

# Alerting monitors
alerting=$(curl -sf \
  -H "DD-API-KEY: $DATADOG_API_KEY" \
  -H "DD-APPLICATION-KEY: $DATADOG_APP_KEY" \
  "$BASE/api/v1/monitor/search?query=status:alert" || echo '{}')
alert_count=$(echo "$alerting" | jq '.counts.status[]? | select(.name == "Alert") | .count // 0' 2>/dev/null || echo "0")
echo "| Alerting monitors | **${alert_count:-0}** | Datadog | \`/api/v1/monitor/search\` | ${alert_count:-0} monitors currently in alert state |" >> "$OUT"

# SLOs
slos=$(curl -sf \
  -H "DD-API-KEY: $DATADOG_API_KEY" \
  -H "DD-APPLICATION-KEY: $DATADOG_APP_KEY" \
  "$BASE/api/v1/slo" || echo '{"data":[]}')
slo_count=$(echo "$slos" | jq '.data | length')
echo "| SLOs | **${slo_count}** | Datadog | \`/api/v1/slo\` | ${slo_count} SLOs configured |" >> "$OUT"

# Dashboard lists
dashboards=$(curl -sf \
  -H "DD-API-KEY: $DATADOG_API_KEY" \
  -H "DD-APPLICATION-KEY: $DATADOG_APP_KEY" \
  "$BASE/api/v1/dashboard/lists/manual" || echo '{"dashboard_lists":[]}')
dash_count=$(echo "$dashboards" | jq '.dashboard_lists | length')
echo "| Dashboard lists | **${dash_count}** | Datadog | \`/api/v1/dashboard/lists\` | ${dash_count} dashboard lists |" >> "$OUT"

# Log indexes
indexes=$(curl -sf \
  -H "DD-API-KEY: $DATADOG_API_KEY" \
  -H "DD-APPLICATION-KEY: $DATADOG_APP_KEY" \
  "$BASE/api/v1/logs/config/indexes" || echo '{"indexes":[]}')
idx_count=$(echo "$indexes" | jq '.indexes | length')
echo "| Log indexes | **${idx_count}** | Datadog | \`/api/v1/logs/config/indexes\` | ${idx_count} log indexes configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: datadog evidence written to $OUT"
