#!/usr/bin/env bash
# .compliance/scripts/github.sh
# Compliance evidence collection for GitHub
# Requires: GH_TOKEN env var (or gh CLI auto-auth in Actions)
# Config:   github.config.json { "repo": "owner/repo" }
# Note: In GitHub Actions, REPO is auto-set to ${{ github.repository }}
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
REPO="${REPO:-$(jq -r '.repo // empty' "$CONFIG")}"

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# GitHub - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: GitHub"
  echo "> Repository: ${REPO}"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Branch protection
default_branch=$(gh api "repos/${REPO}" --jq '.default_branch' 2>/dev/null || echo "main")
protection=$(gh api "repos/${REPO}/branches/${default_branch}/protection" 2>/dev/null || echo "{}")
if echo "$protection" | jq -e '.required_pull_request_reviews' > /dev/null 2>&1; then
  reviewers=$(echo "$protection" | jq '.required_pull_request_reviews.required_approving_review_count // 0')
  echo "| Required reviewers | **${reviewers}** | GitHub | \`/branches/${default_branch}/protection\` | ${reviewers} approving reviews required on ${default_branch} |" >> "$OUT"
else
  echo "| Branch protection | **not configured** | GitHub | \`/branches/${default_branch}/protection\` | No branch protection rules found |" >> "$OUT"
fi

# Dependabot alerts
dep_alerts=$(gh api "repos/${REPO}/dependabot/alerts?state=open&per_page=1" 2>/dev/null || echo "[]")
dep_count=$(echo "$dep_alerts" | jq -r 'if type == "array" then length else 0 end' | tr -d '\n')
echo "| Dependabot alerts (open) | **${dep_count}+** | GitHub | \`/dependabot/alerts\` | ${dep_count}+ open dependency alerts |" >> "$OUT"

# Code scanning alerts
code_alerts=$(gh api "repos/${REPO}/code-scanning/alerts?state=open&per_page=1" 2>/dev/null) || code_alerts="[]"
if echo "$code_alerts" | jq -e 'type == "array"' > /dev/null 2>&1; then
  code_count=$(echo "$code_alerts" | jq -r 'length')
  echo "| Code scanning alerts | **${code_count}+** | GitHub | \`/code-scanning/alerts\` | ${code_count}+ open code scanning alerts |" >> "$OUT"
else
  echo "| Code scanning alerts | **not enabled** | GitHub | \`/code-scanning/alerts\` | Code scanning not configured for this repo |" >> "$OUT"
fi

# Recent merged PRs (30 days)
thirty_days_ago=$(date -u -d '30 days ago' '+%Y-%m-%d' 2>/dev/null || date -u -v-30d '+%Y-%m-%d')
merged=$(gh api "search/issues?q=repo:${REPO}+type:pr+is:merged+merged:>=${thirty_days_ago}" --jq '.total_count' 2>/dev/null || echo "0")
echo "| Merged PRs (30d) | **${merged}** | GitHub | \`/search/issues\` | ${merged} PRs merged in last 30 days |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: github evidence written to $OUT"
