#!/usr/bin/env bash
# .compliance/scripts/gusto.sh
# SOC 2 evidence collection for Gusto
# Requires: GUSTO_API_TOKEN env var
# Config:   gusto.config.json { "company_id": "123456" }
# Privacy: Only aggregate counts — no PII
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
COMPANY_ID=$(jq -r '.company_id' "$CONFIG")

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Gusto - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Gusto"
  echo "> Privacy: Aggregate counts only — no PII"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Employee count
employees=$(curl -sf -H "Authorization: Bearer $GUSTO_API_TOKEN" \
  "https://api.gusto.com/v1/companies/${COMPANY_ID}/employees" || echo "[]")
emp_count=$(echo "$employees" | jq 'length')
echo "| Employee count | **${emp_count}** | Gusto | \`/v1/companies/{id}/employees\` | ${emp_count} employees |" >> "$OUT"

# Benefits
benefits=$(curl -sf -H "Authorization: Bearer $GUSTO_API_TOKEN" \
  "https://api.gusto.com/v1/companies/${COMPANY_ID}/benefits" || echo "[]")
ben_count=$(echo "$benefits" | jq 'length')
echo "| Active benefits | **${ben_count}** | Gusto | \`/v1/companies/{id}/benefits\` | ${ben_count} benefits configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: gusto evidence written to $OUT"
