#!/usr/bin/env bash
# .compliance/scripts/intune.sh
# Compliance evidence collection for Microsoft Intune
# Requires: INTUNE_CLIENT_ID, INTUNE_CLIENT_SECRET, INTUNE_TENANT_ID env vars
# Config:   intune.config.json {}
# Auth: Acquires MS Graph token via client credentials OAuth2
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://graph.microsoft.com"

# Acquire MS Graph token via client credentials
MS_GRAPH_TOKEN=$(curl -sf -X POST \
  "https://login.microsoftonline.com/${INTUNE_TENANT_ID}/oauth2/v2.0/token" \
  -d "client_id=${INTUNE_CLIENT_ID}&client_secret=${INTUNE_CLIENT_SECRET}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&grant_type=client_credentials" \
  | jq -r '.access_token' || echo "")

if [ -z "$MS_GRAPH_TOKEN" ]; then
  {
    echo "# Microsoft Intune - SaaS Evidence"
    echo ""
    echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
    echo "> Tool: Microsoft Intune"
    echo ""
    echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
    echo "|---------|----------------|------|-------------|-------------|"
    echo "| Intune API | **authentication failed** | Intune | \`/oauth2/v2.0/token\` | Could not obtain MS Graph token |"
    echo ""
    echo "*Auto-generated by compliance-evidence scripts.*"
  } > "$OUT"
  echo "FAILED: intune — could not acquire MS Graph token"
  exit 1
fi

{
  echo "# Microsoft Intune - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Microsoft Intune"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Managed devices count
devices=$(curl -sf -H "Authorization: Bearer $MS_GRAPH_TOKEN" \
  "$BASE/v1.0/deviceManagement/managedDevices?\$count=true&\$top=1" \
  -H "ConsistencyLevel: eventual" || echo '{"@odata.count":0}')
dev_count=$(echo "$devices" | jq '.["@odata.count"] // (.value | length) // 0')
echo "| Managed devices | **${dev_count}** | Intune | \`/v1.0/deviceManagement/managedDevices\` | ${dev_count} managed devices |" >> "$OUT"

# Compliance policies
compliance=$(curl -sf -H "Authorization: Bearer $MS_GRAPH_TOKEN" \
  "$BASE/v1.0/deviceManagement/deviceCompliancePolicies" || echo '{"value":[]}')
comp_count=$(echo "$compliance" | jq '.value | length')
echo "| Compliance policies | **${comp_count}** | Intune | \`/v1.0/deviceManagement/deviceCompliancePolicies\` | ${comp_count} compliance policies |" >> "$OUT"

# Compliance status summary
status=$(curl -sf -H "Authorization: Bearer $MS_GRAPH_TOKEN" \
  "$BASE/v1.0/deviceManagement/deviceCompliancePolicyDeviceStateSummary" || echo '{}')
compliant=$(echo "$status" | jq '.compliantDeviceCount // 0')
noncompliant=$(echo "$status" | jq '.nonCompliantDeviceCount // 0')
echo "| Compliance status | **${compliant} compliant, ${noncompliant} non-compliant** | Intune | \`/deviceCompliancePolicyDeviceStateSummary\` | ${compliant} compliant, ${noncompliant} non-compliant devices |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: intune evidence written to $OUT"
