#!/usr/bin/env bash
# .compliance/scripts/jamf.sh
# SOC 2 evidence collection for Jamf Pro
# Requires: JAMF_CLIENT_ID, JAMF_CLIENT_SECRET env vars
# Config:   jamf.config.json { "url": "https://company.jamfcloud.com" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
JAMF_URL=$(jq -r '.url' "$CONFIG")

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Jamf Pro - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Jamf Pro"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Get bearer token via client credentials
TOKEN=$(curl -sf -X POST "$JAMF_URL/api/oauth/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "client_id=$JAMF_CLIENT_ID&client_secret=$JAMF_CLIENT_SECRET&grant_type=client_credentials" \
  | jq -r '.access_token' || echo "")

if [ -z "$TOKEN" ]; then
  echo "| Jamf API | **authentication failed** | Jamf | \`/api/oauth/token\` | Could not obtain bearer token |" >> "$OUT"
else
  # Managed devices count
  devices=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "$JAMF_URL/api/v1/computers-inventory?section=GENERAL&page-size=1" || echo '{"totalCount":0}')
  dev_count=$(echo "$devices" | jq '.totalCount // 0')
  echo "| Managed devices | **${dev_count}** | Jamf | \`/api/v1/computers-inventory\` | ${dev_count} managed computers |" >> "$OUT"

  # FileVault encryption status
  encrypted=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "$JAMF_URL/api/v1/computers-inventory?section=DISK_ENCRYPTION&page-size=200" || echo '{"results":[]}')
  total_enc=$(echo "$encrypted" | jq '.results | length')
  fv_enabled=$(echo "$encrypted" | jq '[.results[] | select(.diskEncryption.fileVaultStatus == "VALID" or .diskEncryption.fileVaultStatus == "ALL_ENCRYPTED")] | length' 2>/dev/null || echo "0")
  echo "| FileVault encryption | **${fv_enabled}/${total_enc}** | Jamf | \`/api/v1/computers-inventory?section=DISK_ENCRYPTION\` | ${fv_enabled} of ${total_enc} devices encrypted |" >> "$OUT"

  # Compliance policies (prestages)
  prestages=$(curl -sf -H "Authorization: Bearer $TOKEN" \
    "$JAMF_URL/api/v2/computer-prestages" || echo '{"results":[]}')
  ps_count=$(echo "$prestages" | jq '.results | length')
  echo "| Enrollment prestages | **${ps_count}** | Jamf | \`/api/v2/computer-prestages\` | ${ps_count} prestage policies configured |" >> "$OUT"
fi

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: jamf evidence written to $OUT"
