#!/usr/bin/env bash
# .compliance/scripts/jira.sh
# SOC 2 evidence collection for Jira
# Requires: JIRA_API_TOKEN, JIRA_EMAIL env vars
# Config:   jira.config.json { "domain": "https://company.atlassian.net", "project": "ENG" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
DOMAIN=$(jq -r '.domain' "$CONFIG")
PROJECT=$(jq -r '.project' "$CONFIG")
AUTH=$(echo -n "$JIRA_EMAIL:$JIRA_API_TOKEN" | base64)

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Jira - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Jira"
  echo "> Project: ${PROJECT}"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Open tickets
open=$(curl -sf -H "Authorization: Basic $AUTH" \
  "$DOMAIN/rest/api/3/search?jql=project%3D${PROJECT}%20AND%20status%21%3DDone&maxResults=0" \
  | jq '.total // 0' || echo "0")
echo "| Open change tickets | **${open}** | Jira | \`/rest/api/3/search\` | ${open} open tickets in ${PROJECT} |" >> "$OUT"

# Resolved in last 30 days
resolved=$(curl -sf -H "Authorization: Basic $AUTH" \
  "$DOMAIN/rest/api/3/search?jql=project%3D${PROJECT}%20AND%20status%3DDone%20AND%20resolved%3E%3D-30d&maxResults=0" \
  | jq '.total // 0' || echo "0")
echo "| Resolved tickets (30d) | **${resolved}** | Jira | \`/rest/api/3/search\` | ${resolved} tickets resolved in last 30 days |" >> "$OUT"

# Workflow statuses
statuses=$(curl -sf -H "Authorization: Basic $AUTH" \
  "$DOMAIN/rest/api/3/project/${PROJECT}/statuses" || echo "[]")
if echo "$statuses" | jq -e '.[0].statuses' > /dev/null 2>&1; then
  status_names=$(echo "$statuses" | jq -r '.[0].statuses[].name' | tr '\n' ', ' | sed 's/,$//')
  echo "| Workflow statuses | **configured** | Jira | \`/project/${PROJECT}/statuses\` | Statuses: ${status_names} |" >> "$OUT"
fi

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: jira evidence written to $OUT"
