#!/usr/bin/env bash
# .compliance/scripts/jumpcloud.sh
# Compliance evidence collection for JumpCloud
# Requires: JUMPCLOUD_API_KEY env var
# Config:   jumpcloud.config.json {}
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://console.jumpcloud.com"

{
  echo "# JumpCloud - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: JumpCloud"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# System users count
users=$(curl -sf -H "x-api-key: $JUMPCLOUD_API_KEY" \
  -H "Content-Type: application/json" \
  "$BASE/api/systemusers?limit=1&skip=0" || echo '{"totalCount":0}')
user_count=$(echo "$users" | jq '.totalCount // 0')
echo "| System users | **${user_count}** | JumpCloud | \`/api/systemusers\` | ${user_count} system users |" >> "$OUT"

# User groups
groups=$(curl -sf -H "x-api-key: $JUMPCLOUD_API_KEY" \
  -H "Content-Type: application/json" \
  "$BASE/api/v2/usergroups" || echo "[]")
group_count=$(echo "$groups" | jq 'length')
echo "| User groups | **${group_count}** | JumpCloud | \`/api/v2/usergroups\` | ${group_count} user groups configured |" >> "$OUT"

# Policies
policies=$(curl -sf -H "x-api-key: $JUMPCLOUD_API_KEY" \
  -H "Content-Type: application/json" \
  "$BASE/api/v2/policies" || echo "[]")
policy_count=$(echo "$policies" | jq 'length')
echo "| Policies | **${policy_count}** | JumpCloud | \`/api/v2/policies\` | ${policy_count} policies configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: jumpcloud evidence written to $OUT"
