#!/usr/bin/env bash
# .compliance/scripts/kandji.sh
# Compliance evidence collection for Kandji
# Requires: KANDJI_API_TOKEN env var
# Config:   kandji.config.json { "subdomain": "company" }
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
SUBDOMAIN=$(jq -r '.subdomain' "$CONFIG")
BASE="https://${SUBDOMAIN}.api.kandji.io"

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Kandji - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Kandji"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Device count
devices=$(curl -sf -H "Authorization: Bearer $KANDJI_API_TOKEN" \
  "$BASE/api/v1/devices" || echo "[]")
dev_count=$(echo "$devices" | jq 'length')
echo "| Managed devices | **${dev_count}** | Kandji | \`/api/v1/devices\` | ${dev_count} managed devices |" >> "$OUT"

# Blueprints (policies)
blueprints=$(curl -sf -H "Authorization: Bearer $KANDJI_API_TOKEN" \
  "$BASE/api/v1/blueprints" || echo "[]")
bp_count=$(echo "$blueprints" | jq 'length')
echo "| Blueprints | **${bp_count}** | Kandji | \`/api/v1/blueprints\` | ${bp_count} blueprints (policies) configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: kandji evidence written to $OUT"
