#!/usr/bin/env bash
# .compliance/scripts/linear.sh
# SOC 2 evidence collection for Linear
# Requires: LINEAR_API_KEY env var
# Config:   linear.config.json {}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Linear - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Linear"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Open issues count
open=$(curl -sf \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"query":"{ issues(filter: { state: { type: { in: [\"started\", \"unstarted\"] } } }) { totalCount } }"}' \
  "https://api.linear.app/graphql" || echo '{}')
open_count=$(echo "$open" | jq '.data.issues.totalCount // 0' 2>/dev/null || echo "0")
echo "| Open issues | **${open_count}** | Linear | GraphQL | ${open_count} started/unstarted issues |" >> "$OUT"

# Teams and workflows
teams=$(curl -sf \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"query":"{ teams { nodes { name states { nodes { name type } } } } }"}' \
  "https://api.linear.app/graphql" || echo '{}')
team_count=$(echo "$teams" | jq '.data.teams.nodes | length' 2>/dev/null || echo "0")
echo "| Teams | **${team_count}** | Linear | GraphQL | ${team_count} teams configured |" >> "$OUT"

# Labels
labels=$(curl -sf \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"query":"{ issueLabels { nodes { name } } }"}' \
  "https://api.linear.app/graphql" || echo '{}')
label_count=$(echo "$labels" | jq '.data.issueLabels.nodes | length' 2>/dev/null || echo "0")
echo "| Issue labels | **${label_count}** | Linear | GraphQL | ${label_count} labels defined |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: linear evidence written to $OUT"
