#!/usr/bin/env bash
# .compliance/scripts/newrelic.sh
# SOC 2 evidence collection for New Relic
# Requires: NEWRELIC_API_KEY, NEWRELIC_ACCOUNT_ID env vars
# Config:   newrelic.config.json { "account_id": "123456" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
ACCOUNT_ID=$(jq -r '.account_id // empty' "$CONFIG")
ACCOUNT_ID="${ACCOUNT_ID:-$NEWRELIC_ACCOUNT_ID}"

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# New Relic - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: New Relic"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Alert policies via NerdGraph
policies=$(curl -sf \
  -H "Api-Key: $NEWRELIC_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"query":"{ actor { account(id: '"$ACCOUNT_ID"') { alerts { policiesSearch { totalCount } } } } }"}' \
  "https://api.newrelic.com/graphql" || echo '{}')
policy_count=$(echo "$policies" | jq '.data.actor.account.alerts.policiesSearch.totalCount // 0' 2>/dev/null || echo "0")
echo "| Alert policies | **${policy_count}** | New Relic | NerdGraph | ${policy_count} alert policies configured |" >> "$OUT"

# Monitored applications (REST API)
apps=$(curl -sf \
  -H "Api-Key: $NEWRELIC_API_KEY" \
  "https://api.newrelic.com/v2/applications.json" || echo '{"applications":[]}')
app_count=$(echo "$apps" | jq '.applications | length')
echo "| Monitored applications | **${app_count}** | New Relic | \`/v2/applications.json\` | ${app_count} applications monitored |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: newrelic evidence written to $OUT"
