#!/usr/bin/env bash
# .compliance/scripts/okta.sh
# Compliance evidence collection for Okta
# Requires: OKTA_API_TOKEN env var
# Config:   okta.config.json { "domain": "https://company.okta.com" }
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
DOMAIN=$(jq -r '.domain' "$CONFIG")

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Okta - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Okta"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Password policy
policy=$(curl -sf -H "Authorization: SSWS $OKTA_API_TOKEN" \
  "$DOMAIN/api/v1/policies?type=PASSWORD&limit=1" || echo "[]")
if echo "$policy" | jq -e '.[0].settings.password.complexity' > /dev/null 2>&1; then
  min_len=$(echo "$policy" | jq -r '.[0].settings.password.complexity.minLength')
  echo "| Password min length | **${min_len} characters** | Okta | \`/api/v1/policies?type=PASSWORD\` | Policy minLength: ${min_len} |" >> "$OUT"
fi

# Active user count (paginate to get true total)
users=$(curl -sf -H "Authorization: SSWS $OKTA_API_TOKEN" \
  "$DOMAIN/api/v1/users?filter=status%20eq%20%22ACTIVE%22&limit=200" || echo "[]")
page_count=$(echo "$users" | jq 'length')
total=$page_count
# If we hit the limit, there are more pages
if [ "$page_count" -eq 200 ]; then
  total="200+"
fi
echo "| Active users | **${total}** | Okta | \`/api/v1/users\` | ${total} active users |" >> "$OUT"

# MFA enrollment (sample first 50 users for rate limit safety)
mfa_count=0
for uid in $(echo "$users" | jq -r '.[0:50] | .[].id'); do
  factors=$(curl -sf -H "Authorization: SSWS $OKTA_API_TOKEN" \
    "$DOMAIN/api/v1/users/$uid/factors" || echo "[]")
  has_mfa=$(echo "$factors" | jq '[.[] | select(.status == "ACTIVE")] | length')
  [ "$has_mfa" -gt 0 ] && mfa_count=$((mfa_count + 1))
  sleep 0.2
done
sampled=$(echo "$users" | jq '.[0:50] | length')
pct=$(( sampled > 0 ? mfa_count * 100 / sampled : 0 ))
echo "| MFA enrollment | **${mfa_count}/${sampled} sampled (${pct}%)** | Okta | \`/api/v1/users/{id}/factors\` | ${mfa_count} of ${sampled} sampled users have active MFA |" >> "$OUT"

# Deactivated users (recent)
deactivated=$(curl -sf -H "Authorization: SSWS $OKTA_API_TOKEN" \
  "$DOMAIN/api/v1/users?filter=status%20eq%20%22DEPROVISIONED%22&limit=5" || echo "[]")
deact_count=$(echo "$deactivated" | jq 'length')
echo "| Recently deactivated | **${deact_count}+** | Okta | \`/api/v1/users?status=DEPROVISIONED\` | ${deact_count}+ deprovisioned users |" >> "$OUT"

# Sign-on policy
signon=$(curl -sf -H "Authorization: SSWS $OKTA_API_TOKEN" \
  "$DOMAIN/api/v1/policies?type=OKTA_SIGN_ON&limit=1" || echo "[]")
if echo "$signon" | jq -e '.[0].name' > /dev/null 2>&1; then
  policy_name=$(echo "$signon" | jq -r '.[0].name')
  echo "| Sign-on policy | **${policy_name}** | Okta | \`/api/v1/policies?type=OKTA_SIGN_ON\` | Active sign-on policy: ${policy_name} |" >> "$OUT"
fi

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: okta evidence written to $OUT"
