#!/usr/bin/env bash
# .compliance/scripts/opsgenie.sh
# SOC 2 evidence collection for Opsgenie
# Requires: OPSGENIE_API_KEY env var
# Config:   opsgenie.config.json {}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://api.opsgenie.com"

{
  echo "# Opsgenie - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Opsgenie"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Escalation policies
esc=$(curl -sf -H "Authorization: GenieKey $OPSGENIE_API_KEY" \
  "$BASE/v2/escalations" || echo '{"data":[]}')
esc_count=$(echo "$esc" | jq '.data | length')
echo "| Escalation policies | **${esc_count}** | Opsgenie | \`/v2/escalations\` | ${esc_count} escalation policies |" >> "$OUT"

# On-call schedules
sched=$(curl -sf -H "Authorization: GenieKey $OPSGENIE_API_KEY" \
  "$BASE/v2/schedules" || echo '{"data":[]}')
sched_count=$(echo "$sched" | jq '.data | length')
echo "| On-call schedules | **${sched_count}** | Opsgenie | \`/v2/schedules\` | ${sched_count} schedules configured |" >> "$OUT"

# Open alerts
alerts=$(curl -sf -H "Authorization: GenieKey $OPSGENIE_API_KEY" \
  "$BASE/v2/alerts?status=open&limit=1" || echo '{"data":[]}')
alert_count=$(echo "$alerts" | jq '.data | length')
echo "| Open alerts | **${alert_count}+** | Opsgenie | \`/v2/alerts\` | ${alert_count}+ open alerts |" >> "$OUT"

# Integrations
integrations=$(curl -sf -H "Authorization: GenieKey $OPSGENIE_API_KEY" \
  "$BASE/v2/integrations" || echo '{"data":[]}')
int_count=$(echo "$integrations" | jq '.data | length')
echo "| Integrations | **${int_count}** | Opsgenie | \`/v2/integrations\` | ${int_count} integrations configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: opsgenie evidence written to $OUT"
