#!/usr/bin/env bash
# .compliance/scripts/pagerduty.sh
# SOC 2 evidence collection for PagerDuty
# Requires: PAGERDUTY_API_TOKEN env var
# Config:   pagerduty.config.json {}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://api.pagerduty.com"

{
  echo "# PagerDuty - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: PagerDuty"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Escalation policies
esc=$(curl -sf -H "Authorization: Token token=$PAGERDUTY_API_TOKEN" \
  -H "Content-Type: application/json" \
  "$BASE/escalation_policies?total=true&limit=1" || echo '{"total":0}')
esc_count=$(echo "$esc" | jq '.total // 0')
echo "| Escalation policies | **${esc_count} configured** | PagerDuty | \`/escalation_policies\` | ${esc_count} escalation policies |" >> "$OUT"

# On-call schedules
sched=$(curl -sf -H "Authorization: Token token=$PAGERDUTY_API_TOKEN" \
  -H "Content-Type: application/json" \
  "$BASE/schedules?total=true&limit=1" || echo '{"total":0}')
sched_count=$(echo "$sched" | jq '.total // 0')
echo "| On-call schedules | **${sched_count} active** | PagerDuty | \`/schedules\` | ${sched_count} on-call schedules |" >> "$OUT"

# Active incidents
inc=$(curl -sf -H "Authorization: Token token=$PAGERDUTY_API_TOKEN" \
  -H "Content-Type: application/json" \
  "$BASE/incidents?total=true&limit=1&statuses%5B%5D=triggered&statuses%5B%5D=acknowledged" || echo '{"total":0}')
inc_count=$(echo "$inc" | jq '.total // 0')
echo "| Active incidents | **${inc_count} open** | PagerDuty | \`/incidents\` | ${inc_count} triggered/acknowledged incidents |" >> "$OUT"

# Services
svc=$(curl -sf -H "Authorization: Token token=$PAGERDUTY_API_TOKEN" \
  -H "Content-Type: application/json" \
  "$BASE/services?total=true&limit=1" || echo '{"total":0}')
svc_count=$(echo "$svc" | jq '.total // 0')
echo "| Monitored services | **${svc_count}** | PagerDuty | \`/services\` | ${svc_count} services configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: pagerduty evidence written to $OUT"
