#!/usr/bin/env bash
# .compliance/scripts/posthog.sh
# Compliance evidence collection for PostHog
# Requires: POSTHOG_PERSONAL_API_KEY env var
# Config:   posthog.config.json (co-located)
# Usage:    bash posthog.sh [-v]
set -uo pipefail

# ── Options ────────────────────────────────────────────
VERBOSE=false

while getopts "v" opt; do
  case $opt in
    v) VERBOSE=true ;;
    *) echo "Usage: $0 [-v]"; exit 1 ;;
  esac
done

log() {
  if $VERBOSE; then
    echo "[$(date -u '+%H:%M:%S')] $*" >&2
  fi
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"

HOST=$(jq -r '.host // "https://app.posthog.com"' "$CONFIG")
PROJECT_ID=$(jq -r '.project_id // empty' "$CONFIG")

log "Config: ${CONFIG}"
log "Host: ${HOST}"
log "Project ID: ${PROJECT_ID:-not set}"

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# PostHog - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: PostHog"
  echo "> Host: ${HOST}"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

API_KEY="${POSTHOG_PERSONAL_API_KEY:-}"
if [ -z "$API_KEY" ]; then
  echo "| Analytics platform | **token not configured** | PostHog | - | POSTHOG_PERSONAL_API_KEY not set |" >> "$OUT"
  echo "" >> "$OUT"
  echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
  echo "OK: posthog evidence written to $OUT (no token)"
  exit 0
fi

# Organization details
log "Fetching organization details..."
result=$(curl -sf -H "Authorization: Bearer ${API_KEY}" \
  "${HOST}/api/organizations/" || echo "{}")
if echo "$result" | jq -e '.results' > /dev/null 2>&1; then
  org_count=$(echo "$result" | jq '.results | length')
  org_name=$(echo "$result" | jq -r '.results[0].name // "unknown"')
  echo "| Organization | **${org_name}** | PostHog | \`/api/organizations/\` | ${org_count} org(s) configured |" >> "$OUT"

  # Member count from first org
  org_id=$(echo "$result" | jq -r '.results[0].id // empty')
  if [ -n "$org_id" ]; then
    members=$(curl -sf -H "Authorization: Bearer ${API_KEY}" \
      "${HOST}/api/organizations/${org_id}/members/" || echo "{}")
    member_count=$(echo "$members" | jq -r 'if type == "array" then length elif .results then .results | length else 0 end')
    echo "| Organization members | **${member_count}** | PostHog | \`/api/organizations/${org_id}/members/\` | ${member_count} members in org |" >> "$OUT"
  fi
fi

# Project/team info
log "Fetching project info..."
if [ -n "$PROJECT_ID" ]; then
  project=$(curl -sf -H "Authorization: Bearer ${API_KEY}" \
    "${HOST}/api/projects/${PROJECT_ID}/" || echo "{}")
  if echo "$project" | jq -e '.id' > /dev/null 2>&1; then
    project_name=$(echo "$project" | jq -r '.name // "unknown"')
    echo "| Project configured | **${project_name}** | PostHog | \`/api/projects/${PROJECT_ID}/\` | Project active |" >> "$OUT"
  fi
fi

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"

log "COMPLETE: posthog evidence written to $OUT"
echo "OK: posthog evidence written to $OUT"
