#!/usr/bin/env bash
# .compliance/scripts/rippling.sh
# SOC 2 evidence collection for Rippling
# Requires: RIPPLING_API_TOKEN env var
# Config:   rippling.config.json {}
# Privacy: Only aggregate counts — no PII
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://api.rippling.com"

{
  echo "# Rippling - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Rippling"
  echo "> Privacy: Aggregate counts only — no PII"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Employee count
employees=$(curl -sf -H "Authorization: Bearer $RIPPLING_API_TOKEN" \
  "$BASE/platform/api/employees" || echo "[]")
emp_count=$(echo "$employees" | jq 'length')
echo "| Employee count | **${emp_count}** | Rippling | \`/platform/api/employees\` | ${emp_count} employees |" >> "$OUT"

# Policies
policies=$(curl -sf -H "Authorization: Bearer $RIPPLING_API_TOKEN" \
  "$BASE/platform/api/policies" || echo "[]")
pol_count=$(echo "$policies" | jq 'length')
echo "| Active policies | **${pol_count}** | Rippling | \`/platform/api/policies\` | ${pol_count} policies configured |" >> "$OUT"

# Managed devices
devices=$(curl -sf -H "Authorization: Bearer $RIPPLING_API_TOKEN" \
  "$BASE/platform/api/devices" || echo "[]")
dev_count=$(echo "$devices" | jq 'length')
echo "| Managed devices | **${dev_count}** | Rippling | \`/platform/api/devices\` | ${dev_count} devices managed |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: rippling evidence written to $OUT"
