#!/usr/bin/env bash
# .compliance/scripts/sentry.sh
# Compliance evidence collection for Sentry
# Requires: SENTRY_AUTH_TOKEN env var
# Config:   sentry.config.json (co-located)
# Usage:    bash sentry.sh [-v]
set -uo pipefail

# ── Options ────────────────────────────────────────────
VERBOSE=false

while getopts "v" opt; do
  case $opt in
    v) VERBOSE=true ;;
    *) echo "Usage: $0 [-v]"; exit 1 ;;
  esac
done

log() {
  if $VERBOSE; then
    echo "[$(date -u '+%H:%M:%S')] $*" >&2
  fi
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"

ORG=$(jq -r '.org // empty' "$CONFIG")
PROJECT=$(jq -r '.project // empty' "$CONFIG")

log "Config: ${CONFIG}"
log "Org: ${ORG}"
log "Project: ${PROJECT}"

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Sentry - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Sentry"
  echo "> Organization: ${ORG}"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

API_TOKEN="${SENTRY_AUTH_TOKEN:-}"
if [ -z "$API_TOKEN" ]; then
  echo "| Error monitoring | **token not configured** | Sentry | - | SENTRY_AUTH_TOKEN not set |" >> "$OUT"
  echo "" >> "$OUT"
  echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
  echo "OK: sentry evidence written to $OUT (no token)"
  exit 0
fi

BASE="https://sentry.io/api/0"

# Project details
log "Fetching project details..."
result=$(curl -sf -H "Authorization: Bearer ${API_TOKEN}" \
  "${BASE}/projects/${ORG}/${PROJECT}/" || echo "{}")
if echo "$result" | jq -e '.slug' > /dev/null 2>&1; then
  platform=$(echo "$result" | jq -r '.platform // "unknown"')
  status=$(echo "$result" | jq -r '.status // "unknown"')
  echo "| Project configured | **${PROJECT} (${platform})** | Sentry | \`/projects/${ORG}/${PROJECT}/\` | Status: ${status} |" >> "$OUT"
fi

log "Fetching unresolved issues..."
# Unresolved issues count (last 30 days)
thirty_days_ago=$(date -u -d '30 days ago' '+%Y-%m-%dT%H:%M:%S' 2>/dev/null || date -u -v-30d '+%Y-%m-%dT%H:%M:%S')
issues=$(curl -sf -H "Authorization: Bearer ${API_TOKEN}" \
  "${BASE}/projects/${ORG}/${PROJECT}/issues/?query=is:unresolved&statsPeriod=30d&per_page=1" -D /tmp/sentry-headers 2>/dev/null || echo "[]")
if [ -f /tmp/sentry-headers ]; then
  # Sentry returns total count in X-Sentry-Total header when available
  total=$(grep -i 'x-hits' /tmp/sentry-headers 2>/dev/null | tr -d '[:space:]' | cut -d: -f2)
  total=${total:-$(echo "$issues" | jq -r 'if type == "array" then length else 0 end')}
  echo "| Unresolved issues (30d) | **${total}** | Sentry | \`/projects/${ORG}/${PROJECT}/issues/\` | ${total} unresolved issues in last 30 days |" >> "$OUT"
  rm -f /tmp/sentry-headers
fi

# Alert rules
log "Fetching alert rules..."
alerts=$(curl -sf -H "Authorization: Bearer ${API_TOKEN}" \
  "${BASE}/projects/${ORG}/${PROJECT}/rules/" || echo "[]")
alert_count=$(echo "$alerts" | jq -r 'if type == "array" then length else 0 end')
echo "| Alert rules configured | **${alert_count}** | Sentry | \`/projects/${ORG}/${PROJECT}/rules/\` | ${alert_count} alert rules defined |" >> "$OUT"

# Team access
log "Fetching team access..."
teams=$(curl -sf -H "Authorization: Bearer ${API_TOKEN}" \
  "${BASE}/projects/${ORG}/${PROJECT}/teams/" || echo "[]")
team_count=$(echo "$teams" | jq -r 'if type == "array" then length else 0 end')
echo "| Teams with access | **${team_count}** | Sentry | \`/projects/${ORG}/${PROJECT}/teams/\` | ${team_count} teams have project access |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"

log "COMPLETE: sentry evidence written to $OUT"
echo "OK: sentry evidence written to $OUT"
