#!/usr/bin/env bash
# .compliance/scripts/slack.sh
# SOC 2 evidence collection for Slack
# Requires: SLACK_BOT_TOKEN env var (scopes: team:read, channels:read)
# Config:   slack.config.json {}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Slack - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Slack"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Workspace info (2FA enforcement)
team=$(curl -sf -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
  "https://slack.com/api/team.info" || echo '{"ok":false}')
if echo "$team" | jq -e '.ok == true' > /dev/null 2>&1; then
  team_name=$(echo "$team" | jq -r '.team.name')
  echo "| Workspace | **${team_name}** | Slack | \`/api/team.info\` | Workspace: ${team_name} |" >> "$OUT"
fi

# Channel count
channels=$(curl -sf -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
  "https://slack.com/api/conversations.list?types=public_channel&limit=1" || echo '{"ok":false}')
if echo "$channels" | jq -e '.ok == true' > /dev/null 2>&1; then
  # Slack doesn't return total in this endpoint; use response_metadata
  has_more=$(echo "$channels" | jq -r '.response_metadata.next_cursor // empty')
  ch_count=$(echo "$channels" | jq '.channels | length')
  label="${ch_count}+"
  [ -z "$has_more" ] && label="${ch_count}"
  echo "| Public channels | **${label}** | Slack | \`/api/conversations.list\` | ${label} public channels |" >> "$OUT"
fi

# Look for incident response channels
inc_channels=$(curl -sf -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
  "https://slack.com/api/conversations.list?types=public_channel&limit=200" || echo '{"ok":false}')
if echo "$inc_channels" | jq -e '.ok == true' > /dev/null 2>&1; then
  inc_count=$(echo "$inc_channels" | jq '[.channels[] | select(.name | test("incident|outage|sev[0-9]|postmortem"; "i"))] | length')
  echo "| Incident channels | **${inc_count}** | Slack | \`/api/conversations.list\` | ${inc_count} channels matching incident naming pattern |" >> "$OUT"
fi

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: slack evidence written to $OUT"
