#!/usr/bin/env bash
# .compliance/scripts/snyk.sh
# Compliance evidence collection for Snyk
# Requires: SNYK_TOKEN env var
# Config:   snyk.config.json { "org_id": "abc-123" }
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
ORG_ID=$(jq -r '.org_id' "$CONFIG")

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://api.snyk.io"

{
  echo "# Snyk - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Snyk"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Monitored projects
projects=$(curl -sf -H "Authorization: token $SNYK_TOKEN" \
  "$BASE/rest/orgs/${ORG_ID}/projects?version=2024-01-23&limit=10" || echo '{"data":[]}')
proj_count=$(echo "$projects" | jq '.data | length')
echo "| Monitored projects | **${proj_count}+** | Snyk | \`/rest/orgs/{id}/projects\` | ${proj_count}+ projects monitored |" >> "$OUT"

# Open vulnerability count
issues=$(curl -sf -H "Authorization: token $SNYK_TOKEN" \
  "$BASE/rest/orgs/${ORG_ID}/issues?version=2024-01-23&status=open&limit=1" || echo '{"data":[]}')
# Snyk REST API pagination — check meta.total if available
issue_count=$(echo "$issues" | jq '.data | length')
echo "| Open vulnerabilities | **${issue_count}+** | Snyk | \`/rest/orgs/{id}/issues\` | ${issue_count}+ open issues |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: snyk evidence written to $OUT"
