#!/usr/bin/env bash
# .compliance/scripts/sonarcloud.sh
# SOC 2 evidence collection for SonarCloud / SonarQube
# Requires: SONAR_TOKEN env var
# Config:   sonarcloud.config.json { "project_key": "org_project", "base_url": "https://sonarcloud.io" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
PROJECT_KEY=$(jq -r '.project_key' "$CONFIG")
BASE_URL=$(jq -r '.base_url // "https://sonarcloud.io"' "$CONFIG")

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# SonarCloud - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: SonarCloud"
  echo "> Project: ${PROJECT_KEY}"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Quality gate status
qg=$(curl -sf -H "Authorization: Bearer $SONAR_TOKEN" \
  "$BASE_URL/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" || echo '{}')
qg_status=$(echo "$qg" | jq -r '.projectStatus.status // "UNKNOWN"')
echo "| Quality gate | **${qg_status}** | SonarCloud | \`/api/qualitygates/project_status\` | Quality gate status: ${qg_status} |" >> "$OUT"

# Open vulnerabilities
vulns=$(curl -sf -H "Authorization: Bearer $SONAR_TOKEN" \
  "$BASE_URL/api/issues/search?types=VULNERABILITY&statuses=OPEN&componentKeys=${PROJECT_KEY}&ps=1" || echo '{"total":0}')
vuln_count=$(echo "$vulns" | jq '.total // 0')
echo "| Open vulnerabilities | **${vuln_count}** | SonarCloud | \`/api/issues/search\` | ${vuln_count} open vulnerabilities |" >> "$OUT"

# Code coverage
coverage=$(curl -sf -H "Authorization: Bearer $SONAR_TOKEN" \
  "$BASE_URL/api/measures/component?component=${PROJECT_KEY}&metricKeys=coverage" || echo '{}')
cov_value=$(echo "$coverage" | jq -r '.component.measures[]? | select(.metric == "coverage") | .value // "N/A"' 2>/dev/null || echo "N/A")
echo "| Code coverage | **${cov_value}%** | SonarCloud | \`/api/measures/component\` | Coverage: ${cov_value}% |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: sonarcloud evidence written to $OUT"
