#!/usr/bin/env bash
# .compliance/scripts/splunk.sh
# SOC 2 evidence collection for Splunk Cloud
# Requires: SPLUNK_TOKEN env var
# Config:   splunk.config.json { "instance": "company" }
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
INSTANCE=$(jq -r '.instance' "$CONFIG")
SKIP_TLS=$(jq -r '.skip_tls_verify // false' "$CONFIG")
BASE="https://${INSTANCE}.splunkcloud.com:8089"

CURL_OPTS=(-sf)
if [ "$SKIP_TLS" = "true" ]; then
  CURL_OPTS+=(-k)  # Only when explicitly opted in via config
fi

OUT="${SOC2_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Splunk Cloud - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Splunk Cloud"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Saved searches (alerts)
searches=$(curl "${CURL_OPTS[@]}" -H "Authorization: Bearer $SPLUNK_TOKEN" \
  "$BASE/services/saved/searches?count=0&output_mode=json" || echo '{"entry":[]}')
search_count=$(echo "$searches" | jq '.entry | length')
echo "| Saved searches | **${search_count}** | Splunk | \`/services/saved/searches\` | ${search_count} saved searches/alerts configured |" >> "$OUT"

# Indexes
indexes=$(curl "${CURL_OPTS[@]}" -H "Authorization: Bearer $SPLUNK_TOKEN" \
  "$BASE/services/data/indexes?output_mode=json" || echo '{"entry":[]}')
idx_count=$(echo "$indexes" | jq '.entry | length')
echo "| Indexes | **${idx_count}** | Splunk | \`/services/data/indexes\` | ${idx_count} indexes configured |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by soc2-evidence scripts.*" >> "$OUT"
echo "OK: splunk evidence written to $OUT"
