#!/usr/bin/env bash
# .compliance/scripts/statuspage.sh
# Compliance evidence collection for Statuspage
# Requires: STATUSPAGE_API_KEY env var
# Config:   statuspage.config.json { "page_id": "abc123" }
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/$(basename "$0" .sh).config.json"
PAGE_ID=$(jq -r '.page_id' "$CONFIG")

OUT="${COMPLIANCE_EVIDENCE_DIR:-.compliance/evidence/saas}/$(basename "$0" .sh)-evidence.md"
mkdir -p "$(dirname "$OUT")"

BASE="https://api.statuspage.io"

{
  echo "# Statuspage - SaaS Evidence"
  echo ""
  echo "> Scan date: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "> Tool: Statuspage"
  echo ""
  echo "| Control | Extracted Value | Tool | API Endpoint | Raw Evidence |"
  echo "|---------|----------------|------|-------------|-------------|"
} > "$OUT"

# Components monitored
components=$(curl -sf -H "Authorization: OAuth $STATUSPAGE_API_KEY" \
  "$BASE/v1/pages/${PAGE_ID}/components" || echo "[]")
comp_count=$(echo "$components" | jq 'length')
echo "| Components monitored | **${comp_count}** | Statuspage | \`/v1/pages/{id}/components\` | ${comp_count} components being monitored |" >> "$OUT"

# Active incidents
incidents=$(curl -sf -H "Authorization: OAuth $STATUSPAGE_API_KEY" \
  "$BASE/v1/pages/${PAGE_ID}/incidents/unresolved" || echo "[]")
inc_count=$(echo "$incidents" | jq 'length')
echo "| Unresolved incidents | **${inc_count}** | Statuspage | \`/v1/pages/{id}/incidents/unresolved\` | ${inc_count} unresolved incidents |" >> "$OUT"

echo "" >> "$OUT"
echo "*Auto-generated by compliance-evidence scripts.*" >> "$OUT"
echo "OK: statuspage evidence written to $OUT"
